### ISSUE TITLE
Migration to terraform 0.13

### ISSUE THREAD

**Issue by Lethgir** [LeanerCloud/terraform-aws-autospotting#35]
When i want to migrate to terraform 0.13, I get the following error : 
```
Error: Unsupported Terraform Core version

  on .terraform/modules/autospotting.aws_lambda_function.label/versions.tf line 2, in terraform:
   2:   required_version = "~> 0.12.0"

Module module.autospotting.module.aws_lambda_function.module.label (from
git::https://github.com/cloudposse/terraform-null-label.git?ref=0.13.0) does
not support Terraform version 0.13.4. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```

I wonder if the issue is only due to `versions.tf`.

**Comment by cristim** [comment]
yes, try to relax the version requirement

Later edit: this should work with the latest version 0.1.7, which I just released a few minutes ago. We now use a more recent version of the null-label module which should support Terraform 0.13. This hasn't seen much testing, so please let me know if you notice any issues.

Also please be aware of the fact that I also recently merged a huge code change in AutoSpotting which hasn't yet been tested so much yet, especially with Terraform. It should still work in the legacy mode but very probably the Terraform code needs a bunch of changes to enable the new functionality.

So if you notice anything strange please report back.

**Comment by Lethgir** [comment]
Thanks for your fast answer !
I had the version `0.1.1` so there is some changes to manage.

I encounter 3 times the error `Error: Provider configuration not present` for these resources : 
 - module.autospotting.module.aws_lambda_function.module.label.data.null_data_source.tags_as_list_of_maps[0]
- module.autospotting.module.aws_lambda_function.aws_lambda_function.autospotting_from_s3[0]
- module.autospotting.module.label.data.null_data_source.tags_as_list_of_maps[0]

Can you confirm I can remove the state for the both `null_data_source` and move the state of the lambda function to the following name : 
- module.autospotting.module.aws_lambda_function.aws_lambda_function.autospotting

**Comment by cristim** [comment]
To be honest I haven't tried the Terraform code recently, and especially the migration path from older versions.

A while  ago we used to have two Lambda functions, if I remember correctly it was because  the Zip could be either referenced from S3 or generated locally.

This was simplified a few months ago so that we now have a single Lambda function that can use both S3 and local files. The upgrade from the older version may require you to delete/move those resources from the state, but it should be harmless.

But I would recommend you to keep backups of the state file, just in case you need to revert.
