### ISSUE TITLE
[Feature] Support price-capacity-optimized

### ISSUE THREAD

**Issue by fauzanelka** [LeanerCloud/terraform-aws-autospotting#43]
[Here](https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/)

**Comment by cristim** [comment]
@fauzanelka thanks for reporting this issue.

AutoSpotting's custom allocation strategy is actually much like price-capacity-optimized, but instead of just considering the hourly price, by default it also automatically prioritizes newer instance generations when available, so that in addition to the cost savings you also get better performance and lower carbon emissions.

Since our implementation is more advanced, although we can easily expose  this field, I'd rather not expose it as it can confuse some users who would use it instead of our implementation.

I hope this answers your question.
